export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const MODIFICATION_EMAIL = 'MODIFICATION_EMAIL';
export const MODIFICATION_PASSWORD = 'MODIFICATION_PASSWORD';
export const MODIFICATION_NAME = 'MODIFICATION_NAME';
export const MODIFICATION_REGISTER_USER_ERROR_MESSAGE = 'MODIFICATION_REGISTER_USER_ERROR_MESSAGE';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const MODIFICATION_LOGIN_PROGRESS_START = 'MODIFICATION_LOGIN_PROGRESS_START';
export const MODIFICATION_LOGIN_PROGRESS_STOP = 'MODIFICATION_LOGIN_PROGRESS_STOP';
export const MODIFICATION_SIGNUP_PROGRESS = 'MODIFICATION_SIGNUP_PROGRESS';
export const SIGNUP_IN_PROGRESS = 'SIGNUP_IN_PROGRESS';


export const RESET_APP_REDUCER = 'RESET_APP_REDUCER';
export const MODIFICATION_CONTACT_EMAIL = 'MODIFICATION_CONTACT_EMAIL';
export const MODIFICATION_CONTACT_NAME = 'MODIFICATION_CONTACT_NAME';
export const ADD_CONTACT_ERR = 'ADD_CONTACT_ERR';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const LIST_USER_CONTACTS = 'LIST_USER_CONTACTS';
export const MODIFICATION_MESSAGE = 'MODIFICATION_MESSAGE';
export const LIST_USER_CHATTING = 'LIST_USER_CHATTING';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const RESET_AUTHENTICATION_REDUCER = 'RESET_AUTHENTICATION_REDUCER';
export const LIST_USER_CONVERSATION = 'LIST_USER_CONVERSATION';
export const LOGOUT_IN_PROGRESS = 'LOGOUT_IN_PROGRESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const IS_USER_LOGIN = 'IS_USER_LOGIN';

export const MODIFICATION_SIGNUP_EMAIL = 'MODIFICATION_SIGNUP_EMAIL';
export const MODIFICATION_SIGNUP_PASSWORD = 'MODIFICATION_SIGNUP_PASSWORD';

export const RESET_SIGNUP_FORM = 'RESET_SIGNUP_FORM';
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS';
export const LIST_NOTIFICATIONS = 'LIST_NOTIFICATIONS';
export const MODIFICATION_PHONE_NUMBER = 'MODIFICATION_PHONE_NUMBER';

export const MODIFICATION_TITLE_ADMIN = 'MODIFICATION_TITLE_ADMIN';
export const SUBMIT_PHONE_NUMBER = 'SUBMIT_PHONE_NUMBER';
export const SUBMIT_PHONE_NUMBER_IN_PROGRESS = 'SUBMIT_PHONE_NUMBER_IN_PROGRESS';
export const MODIFICATION_VERIFY_CODE = 'MODIFICATION_VERIFY_CODE';
export const SUBMIT_PHONE_NUMBER_SUCCESS = 'SUBMIT_PHONE_NUMBER_SUCCESS';
export const RE_ENTER_PHONE_NUMBER = 'RE_ENTER_PHONE_NUMBER';
export const RE_SMS_VERIFICATION_CODE_IN_PROGRESS = 'RE_SMS_VERIFICATION_CODE_IN_PROGRESS';
export const RE_SMS_VERIFICATION_CODE_SUCCESS = 'RE_SMS_VERIFICATION_CODE_SUCCESS';
export const RESET_INPUT_VERIFICATION_CODE_FORM = 'RESET_INPUT_VERIFICATION_CODE_FORM';
export const MODIFICATION_DATETIMELOGIN_SESSION = 'MODIFICATION_DATETIMELOGIN_SESSION';
export const SUCCESS_LOGIN_SESSION = 'SUCCESS_LOGIN_SESSION';
export const MODIFICATION_PASSWORD_SESSION = 'MODIFICATION_PASSWORD_SESSION';
export const MODIFICATION_USERNAME_SESSION = 'MODIFICATION_USERNAME_SESSION';
export const SESSION_LOGIN_IN_PROGRESS = 'SESSION_LOGIN_IN_PROGRESS';
export const FAILED_LOGIN_SESSION = 'FAILED_LOGIN_SESSION';
export const SESSION_LOG_OUT = 'SESSION_LOG_OUT';
export const GOTO_SUB_ADMIN_PAGE = 'GOTO_SUB_ADMIN_PAGE';

//Splash
export const MODIFY_LOADING_DATA_USERS_IN_PROGRESS = 'MODIFY_LOADING_DATA_USERS_IN_PROGRESS';
export const LOADING_DATA_USERS_IN_PROGRESS = 'LOADING_DATA_USERS_IN_PROGRESS';
export const LOADING_DATA_USERS_DONE = 'LOADING_DATA_USERS_DONE';

//setting
export const SAVE_SETTING = 'SAVE_SETTING';
export const SAVE_SETTING_IN_PROGRESS = 'SAVE_SETTING_IN_PROGRESS';
export const SETTING_SET_NO_PHOTO = 'SETTING_SET_NO_PHOTO';
export const SETTING_SET_ABSEN_MODE = 'SETTING_SET_ABSEN_MODE';

//data siswa
export const FETCH_ALL_DATA_SISWA = 'FETCH_ALL_DATA_SISWA';
export const SAVE_DATA_SISWA = 'SAVE_DATA_SISWA';
export const SAVE_DATA_SISWA_ERROR = 'SAVE_DATA_SISWA_ERROR';
export const SAVE_DATA_SISWA_INTERNAL_ERROR = 'SAVE_DATA_SISWA_INTERNAL_ERROR';
export const SAVE_DATA_SISWA_IN_PROGRESS = 'SAVE_DATA_SISWA_IN_PROGRESS';
export const UPDATE_DATA_SISWA_IN_PROGRESS = 'UPDATE_DATA_SISWA_IN_PROGRESS';
export const UPDATE_DATA_SISWA = 'UPDATE_DATA_SISWA';
export const UPDATE_DATA_SISWA_ERROR = 'UPDATE_DATA_SISWA_ERROR';
export const FETCH_ONE_DATA_SISWA = 'FETCH_ONE_DATA_SISWA';
export const OPEN_MODAL_FORM_UPDATE_DATA_SISWA = 'OPEN_MODAL_FORM_UPDATE_DATA_SISWA';
export const SET_MODAL_FORM_PHOTO = 'SET_MODAL_FORM_PHOTO';
export const CLOSE_MODAL_FORM = 'CLOSE_MODAL_FORM';
export const OPEN_MODAL_FORM = 'OPEN_MODAL_FORM';
export const UPDATE_DATA_SISWA_INTERNAL_ERROR = 'UPDATE_DATA_SISWA_INTERNAL_ERROR';

export const SISWA_DELETE_DATA_IN_PROGRESS = 'SISWA_DELETE_DATA_IN_PROGRESS';
export const SISWA_DELETE_DATA_SUCCESS = 'SISWA_DELETE_DATA_SUCCESS';
export const SISWA_DELETE_DATA_ERROR = 'SISWA_DELETE_DATA_ERROR';
export const SISWA_DELETE_DATA_INTERNAL_ERROR = 'SISWA_DELETE_DATA_INTERNAL_ERROR';

//Gurustaff
export const GURUSTAFF_SAVE_DATA_SUCCESS = 'GURUSTAFF_SAVE_DATA_SUCCESS';
export const GURUSTAFF_SAVE_DATA_IN_PROGRESS = 'GURUSTAFF_SAVE_DATA_IN_PROGRESS';
export const GURUSTAFF_SAVE_DATA_ERROR = 'GURUSTAFF_SAVE_DATA_ERROR';
export const GURUSTAFF_SAVE_DATA_INTERNAL_ERROR = 'GURUSTAFF_SAVE_DATA_INTERNAL_ERROR';
export const GURUSTAFF_UPDATE_DATA_IN_PROGRESS = 'GURUSTAFF_UPDATE_DATA_IN_PROGRESS';
export const GURUSTAFF_UPDATE_DATA_SUCCESS = 'GURUSTAFF_UPDATE_DATA_SUCCESS';
export const GURUSTAFF_UPDATE_DATA_ERROR = 'GURUSTAFF_UPDATE_DATA_ERROR';
export const GURUSTAFF_UPDATE_DATA_INTERNAL_ERROR = 'GURUSTAFF_UPDATE_DATA_INTERNAL_ERROR';
export const GURUSTAFF_DELETE_DATA_IN_PROGRESS = 'GURUSTAFF_DELETE_DATA_IN_PROGRESS';
export const GURUSTAFF_DELETE_DATA_SUCCESS = 'GURUSTAFF_DELETE_DATA_SUCCESS';
export const GURUSTAFF_DELETE_DATA_ERROR = 'GURUSTAFF_DELETE_DATA_ERROR';
export const GURUSTAFF_DELETE_DATA_INTERNAL_ERROR = 'GURUSTAFF_DELETE_DATA_INTERNAL_ERROR';
export const GURUSTAFF_FETCH_ALL = 'GURUSTAFF_FETCH_ALL';
export const GURUSTAFF_FETCH_ONE = 'GURUSTAFF_FETCH_ONE';
export const GURUSTAFF_OPEN_MODAL_FORM_UPDATE = 'GURUSTAFF_OPEN_MODAL_FORM_UPDATE';
export const GURUSTAFF_CLOSE_MODAL_FORM = 'GURUSTAFF_CLOSE_MODAL_FORM';
export const GURUSTAFF_OPEN_MODAL_FORM = 'GURUSTAFF_OPEN_MODAL_FORM';
export const GURUSTAFF_SET_MODAL_FORM_PHOTO = 'GURUSTAFF_SET_MODAL_FORM_PHOTO';

//user
export const USER_SAVE_DATA_SUCCESS = 'USER_SAVE_DATA_SUCCESS';
export const USER_SAVE_DATA_IN_PROGRESS = 'USER_SAVE_DATA_IN_PROGRESS';
export const USER_SAVE_DATA_ERROR = 'USER_SAVE_DATA_ERROR';
export const USER_SAVE_DATA_INTERNAL_ERROR = 'USER_SAVE_DATA_INTERNAL_ERROR';
export const USER_UPDATE_DATA_IN_PROGRESS = 'USER_UPDATE_DATA_IN_PROGRESS';
export const USER_UPDATE_DATA_SUCCESS = 'USER_UPDATE_DATA_SUCCESS';
export const USER_UPDATE_DATA_ERROR = 'USER_UPDATE_DATA_ERROR';
export const USER_UPDATE_DATA_INTERNAL_ERROR = 'USER_UPDATE_DATA_INTERNAL_ERROR';
export const USER_DELETE_DATA_IN_PROGRESS = 'USER_DELETE_DATA_IN_PROGRESS';
export const USER_DELETE_DATA_SUCCESS = 'USER_DELETE_DATA_SUCCESS';
export const USER_DELETE_DATA_ERROR = 'USER_DELETE_DATA_ERROR';
export const USER_DELETE_DATA_INTERNAL_ERROR = 'USER_DELETE_DATA_INTERNAL_ERROR';
export const USER_FETCH_ALL = 'USER_FETCH_ALL';
export const USER_FETCH_ONE = 'USER_FETCH_ONE';
export const USER_OPEN_MODAL_FORM_UPDATE = 'USER_OPEN_MODAL_FORM_UPDATE';
export const USER_CLOSE_MODAL_FORM = 'USER_CLOSE_MODAL_FORM';
export const USER_OPEN_MODAL_FORM = 'USER_OPEN_MODAL_FORM';
export const USER_SET_MODAL_FORM_PHOTO = 'USER_SET_MODAL_FORM_PHOTO';
export const USER_FETCH_ALL_STATIC_DATA = 'USER_FETCH_ALL_STATIC_DATA';
export const USER_OPEN_FORM_UPDATE = 'USER_OPEN_FORM_UPDATE';
export const USER_REDUCER_RESET = 'USER_REDUCER_RESET';


//SESSION
export const SESSION_UPDATE_DATA_DETAIL = 'SESSION_UPDATE_DATA_DETAIL';
export const SESSION_SET_PHOTO_PROFILE_BUFFER = 'SESSION_SET_PHOTO_PROFILE_BUFFER';

//absen
export const ABSEN_SAVE_DATA_SUCCESS = 'ABSEN_SAVE_DATA_SUCCESS';
export const ABSEN_SAVE_DATA_IN_PROGRESS = 'ABSEN_SAVE_DATA_IN_PROGRESS';
export const ABSEN_SAVE_DATA_ERROR = 'ABSEN_SAVE_DATA_ERROR';
export const ABSEN_SAVE_DATA_INTERNAL_ERROR = 'ABSEN_SAVE_DATA_INTERNAL_ERROR';
export const ABSEN_UPDATE_DATA_IN_PROGRESS = 'ABSEN_UPDATE_DATA_IN_PROGRESS';
export const ABSEN_UPDATE_DATA_SUCCESS = 'ABSEN_UPDATE_DATA_SUCCESS';
export const ABSEN_UPDATE_DATA_ERROR = 'ABSEN_UPDATE_DATA_ERROR';
export const ABSEN_UPDATE_DATA_INTERNAL_ERROR = 'ABSEN_UPDATE_DATA_INTERNAL_ERROR';
export const ABSEN_DELETE_DATA_IN_PROGRESS = 'ABSEN_DELETE_DATA_IN_PROGRESS';
export const ABSEN_DELETE_DATA_SUCCESS = 'ABSEN_DELETE_DATA_SUCCESS';
export const ABSEN_DELETE_DATA_ERROR = 'ABSEN_DELETE_DATA_ERROR';
export const ABSEN_DELETE_DATA_INTERNAL_ERROR = 'ABSEN_DELETE_DATA_INTERNAL_ERROR';
export const ABSEN_FETCH_ALL = 'ABSEN_FETCH_ALL';
export const ABSEN_FETCH_ONE = 'ABSEN_FETCH_ONE';
export const ABSEN_FETCH_ALL_GURUSTAFF = 'ABSEN_FETCH_ALL_GURUSTAFF';
export const ABSEN_FETCH_ALL_SISWA = 'ABSEN_FETCH_ALL_SISWA';

export const ABSEN_OPEN_MODAL_FORM_UPDATE = 'ABSEN_OPEN_MODAL_FORM_UPDATE';
export const ABSEN_CLOSE_MODAL_FORM = 'ABSEN_CLOSE_MODAL_FORM';
export const ABSEN_OPEN_MODAL_FORM = 'ABSEN_OPEN_MODAL_FORM';
export const ABSEN_SET_MODAL_FORM_PHOTO = 'ABSEN_SET_MODAL_FORM_PHOTO';
export const ABSEN_INPUT_SCANNER_ID_ON_CHANGE = 'ABSEN_INPUT_SCANNER_ID_ON_CHANGE';
export const ABSEN_SET_DATA_DETAIL = 'ABSEN_SET_DATA_DETAIL';
export const ABSEN_CLEAR_DATA_DETAIL = 'ABSEN_CLEAR_DATA_DETAIL';
export const ABSEN_SET_INPUT_TEXT_FROM_EMPTY = 'ABSEN_SET_INPUT_TEXT_FROM_EMPTY';


//absences
export const FETCH_ALL_DATA_ABSEN_SISWA_SUCCESS = 'FETCH_ALL_DATA_ABSEN_SISWA_SUCCESS';
export const FETCH_ALL_DATA_ABSEN_GURU_SUCCESS = 'FETCH_ALL_DATA_ABSEN_GURU_SUCCESS';
